# Generated by Django 4.0.6 on 2023-09-25 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='code',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='linenos',
        ),
    ]
